# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0
    hooks:
      - id: check-added-large-files # Prevent giant files from being committed
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-executables-have-shebangs # Ensures that (non-binary) executables have a shebang.
      - id: check-json # This hook checks json files for parseable syntax.
      - id: check-yaml # This hook checks yaml files for parseable syntax.
      - id: end-of-file-fixer # Ensures that a file is either empty, or ends with one newline.
      - id: pretty-format-json # This hook sets a standard for formatting JSON files.
        args: [--autofix, --no-ensure-ascii]
      - id: trailing-whitespace # This hook trims trailing whitespace.
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.11.2
    hooks:
      # Run the linter.
      - id: ruff
      # Run the formatter.
      - id: ruff-format
