language: python

dist: bionic
sudo: false

before_install:
  - python --version
  - uname -a
  - lsb_release -a

install:
  - pip install tox-travis==0.11 tox==3.7.0


script:
  - tox --parallel auto

python:
  - "2.7"
  - "3.6"
  - "3.7"
  - "3.8"
