"""
Package setup.

Set me up with `python setup.py bdist_wheel --universal`
"""
import json
import io
import pprint
from setuptools import setup

# Get long description from readme
with io.open("README.md", "rt", encoding="utf8") as readmefile:
    README = readmefile.read()

# Convert emojilib json file to python dictionary, so we don't have the parse
# penalty at runtime
with io.open("emojilib/emojis.json", "rt", encoding="utf8") as emojifile:
    EMOJI_LIB_DATA = json.load(emojifile)
    with open("emoji_fzf_emojilib.py", "w") as genfile:
        genfile.write(
            """\"\"\"
Emoji python alias file, autogenerated.
\"\"\"

"""
        )
        genfile.write("EMOJIS = {}".format(pprint.pformat(EMOJI_LIB_DATA)))


setup(
    # I think using `-` instead of `_` is more user-friendly, but due to python
    # import directives not allowing `-`, keep everything consistent with `_`.
    name="emoji-fzf",
    version="0.1.0",
    description="Emoji searcher for use with fzf",
    author="Noah Pendleton",
    author_email="2538614+noahp@users.noreply.github.com",
    url="https://github.com/noahp/emoji-fzf",
    project_urls={
        "Code": "https://github.com/noahp/emoji-fzf",
        "Issue tracker": "https://github.com/noahp/emoji-fzf/issues",
    },
    long_description=README,
    long_description_content_type="text/markdown",
    install_requires=["click"],
    # using markdown as pypi description:
    # https://dustingram.com/articles/2018/03/16/markdown-descriptions-on-pypi
    setup_requires=["setuptools>=38.6.0", "wheel>=0.31.0", "twine>=1.11.0"],
    py_modules=["emoji_fzf", "emoji_fzf_emojilib"],
    entry_points={"console_scripts": ["emoji-fzf = emoji_fzf:cli"]},
    classifiers=[
        "License :: OSI Approved :: MIT License",
        "Programming Language :: Python :: 2.7",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3.7",
        "Operating System :: OS Independent",
    ],
)
